// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://psdcgtmeixlpjqceqkix.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBzZGNndG1laXhscGpxY2Vxa2l4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzc5MDk1MTgsImV4cCI6MjA1MzQ4NTUxOH0.Uq07A_IbtALcNSfZ0jOa_nDmtmY0t2Kr9Z505XXfLD0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);